



























};  ],    '/((?!_next/static|_next/image|favicon.ico).*)',     */     * - favicon.ico (favicon file)     * - _next/image (image optimization files)     * - _next/static (static files)     * Match all request paths except:    /*  matcher: [  // Only run middleware on specific pathsexport const config = {}  return NextResponse.next();  // }  //   return NextResponse.redirect(new URL('/form', request.url))  // if (!session && request.nextUrl.pathname.startsWith('/profile')) {  // const session = request.cookies.get('session')?.value  // Here you could add authentication checks    console.log(`Request to ${request.nextUrl.pathname}`);  // Example middleware to log requestsexport function middleware(request: NextRequest) {import type { NextRequest } from 'next/server';import { NextResponse } from 'next/server';