




































}  );    </Nav>      </NavList>        </NavItem>          <Link href="/profile">Profile</Link>        <NavItem active={pathname === '/profile'}>        </NavItem>          <Link href="/form">Registration</Link>        <NavItem active={pathname === '/form'}>        </NavItem>          <Link href="/">Home</Link>        <NavItem active={pathname === '/'}>      <NavList>    <Nav>  return (    const pathname = usePathname();export default function Navigation() {`;  font-weight: ${(props: { active: boolean }) => (props.active ? 'bold' : 'normal')};const NavItem = styled.li``;  gap: 1.5rem;  list-style: none;  display: flex;const NavList = styled.ul``;  margin-bottom: 2rem;const Nav = styled.nav`import styled from 'styled-components';import { usePathname } from 'next/navigation';import Link from 'next/link';