


































export default SubmitButton;};  return <Button type="submit" disabled={disabled}>{text}</Button>;const SubmitButton = ({ text, disabled }: SubmitButtonProps) => {}  disabled?: boolean;  text: string;interface SubmitButtonProps {`;  }    cursor: not-allowed;    background-color: #ccc;  &:disabled {    }    background-color: #0051a2;  &:hover {    transition: background-color 0.3s;  cursor: pointer;  font-weight: 500;  font-size: 1rem;  padding: 0.75rem 1.5rem;  border-radius: 4px;  border: none;  color: white;  background-color: #0070f3;const Button = styled.button`import styled from "styled-components";'use client';