





























































}  );    </ErrorContainer>      </ResetButton>        Try again      <ResetButton onClick={reset}>      </ErrorText>        An error occurred while trying to display this page. Please try again.      <ErrorText>      <ErrorTitle>Something went wrong!</ErrorTitle>    <ErrorContainer>  return (  }, [error]);    console.error(error);  useEffect(() => {}) {  reset: () => void;  error: Error & { digest?: string };}: {  reset,  error,export default function Error({`;  }    background-color: #0051a2;  &:hover {    cursor: pointer;  font-weight: 500;  font-size: 1rem;  padding: 0.75rem 1.5rem;  border-radius: 4px;  border: none;  color: white;  background-color: #0070f3;const ResetButton = styled.button``;  margin-bottom: 1.5rem;const ErrorText = styled.p``;  margin-bottom: 1rem;  color: #e00;const ErrorTitle = styled.h2``;  margin: 0 auto;  max-width: 800px;  padding: 2rem;  justify-content: center;  align-items: center;  flex-direction: column;  display: flex;const ErrorContainer = styled.div`import styled from 'styled-components';import { useEffect } from 'react';'use client';