


















































}  );    </NotFoundContainer>      </HomeLink>        Return to Home      <HomeLink href="/">      </NotFoundText>        The page you are looking for does not exist or has been moved.      <NotFoundText>      <NotFoundTitle>404 - Page Not Found</NotFoundTitle>    <NotFoundContainer>  return (export default function NotFound() {`;  }    background-color: #0051a2;  &:hover {    font-weight: 500;  font-size: 1rem;  padding: 0.75rem 1.5rem;  border-radius: 4px;  text-decoration: none;  color: white;  background-color: #0070f3;const HomeLink = styled(Link)``;  margin-bottom: 1.5rem;const NotFoundText = styled.p``;  margin-bottom: 1rem;  font-size: 2rem;const NotFoundTitle = styled.h2``;  margin: 0 auto;  max-width: 800px;  padding: 2rem;  justify-content: center;  align-items: center;  flex-direction: column;  display: flex;const NotFoundContainer = styled.div`import styled from 'styled-components';import Link from 'next/link';'use client';