


























}  );    </StyleSheetManager>      {children}    <StyleSheetManager sheet={styledComponentsStyleSheet.instance}>  return (  if (typeof window !== 'undefined') return <>{children}</>;  });    return <>{styles}</>;    styledComponentsStyleSheet.instance.clearTag();    const styles = styledComponentsStyleSheet.getStyleElement();  useServerInsertedHTML(() => {  const [styledComponentsStyleSheet] = useState(() => new ServerStyleSheet());}) {  children: React.ReactNode;}: {  children,export default function StyledComponentsRegistry({import { ServerStyleSheet, StyleSheetManager } from 'styled-components';import { useServerInsertedHTML } from 'next/navigation';import React, { useState } from 'react';'use client';