




















}  );    </ProfileContainer>      <ProfileComponent />      <Title>Registered Users</Title>    <ProfileContainer>  return (export default function Profile() {`;  text-align: center;  margin-bottom: 2rem;const Title = styled.h1``;  margin: 0 auto;  max-width: 800px;const ProfileContainer = styled.div`import styled from 'styled-components';import ProfileComponent from '../components/Profile';